//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPAssgnmnt3V3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOPAssgnmnt3V3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A repository is like a folder for your project. Your project&apos;s repository contains all of your project&apos;s files and stores each file&apos;s revision history. You can also discuss and manage your project&apos;s work within the repository.
        ///
        ///You can own repositories individually, or you can share ownership of repositories with other people in an organization.
        ///
        ///You can restrict who has access to a repository by choosing the repository&apos;s visibility. For more information, see &quot;About repository visibility.&quot;.
        /// </summary>
        internal static string GitRepositories_1a {
            get {
                return ResourceManager.GetString("GitRepositories_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A repository is like a folder for your project. Your project&apos;s repository contains all of your project&apos;s files and stores each file&apos;s revision history. You can also discuss and manage your project&apos;s work within the repository.
        ///
        ///You can own repositories individually, or you can share ownership of repositories with other people in an organization.
        ///
        ///You can restrict who has access to a repository by choosing the repository&apos;s visibility. For more information, see &quot;About repository visibility.&quot;.
        /// </summary>
        internal static string GitRepositories_1b {
            get {
                return ResourceManager.GetString("GitRepositories_1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub&apos;s collaborative approach to development depends on publishing commits from your local repository for other people to view, fetch, and update.
        ///
        ///A remote URL is Git&apos;s fancy way of saying &quot;the place where your code is stored.&quot; That URL could be your repository on GitHub, or another user&apos;s fork, or even on a completely different server.
        ///
        ///You can only push to two types of URL addresses:
        ///
        ///An HTTPS URL like https://github.com/user/repo.git
        ///An SSH URL, like git@github.com:user/repo.git
        ///Git associates [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitRepositories_2a {
            get {
                return ResourceManager.GetString("GitRepositories_2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub&apos;s collaborative approach to development depends on publishing commits from your local repository for other people to view, fetch, and update.
        ///
        ///A remote URL is Git&apos;s fancy way of saying &quot;the place where your code is stored.&quot; That URL could be your repository on GitHub, or another user&apos;s fork, or even on a completely different server.
        ///
        ///You can only push to two types of url addresses:
        ///
        ///An HTTPS URL like https://github.com/user/repo.git
        ///An SSH URL, like git@github.com:user/repo.git
        ///Git associates [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitRepositories_2b {
            get {
                return ResourceManager.GetString("GitRepositories_2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After initializing a pull request, you&apos;ll see a review page that shows a high-level overview of the changes between your branch (the compare branch) and the repository&apos;s base branch. You can add a summary of the proposed changes, review the changes made by commits, add labels, milestones, and assignees, and @mention individual contributors or teams. For more information, see &quot;Creating a pull request.&quot;
        ///
        ///Once you&apos;ve created a pull request, you can push commits from your topic branch to add them to your exis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitRepositories_3a {
            get {
                return ResourceManager.GetString("GitRepositories_3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After initializing a pull request, you will see a review page that shows a high-level overview of the changes between your branch (the compare branch) and the repository&apos;s base branch. You can add a summary of the proposed changes, review the changes made by commits, add labels, milestones, and assignees, and @mention individual contributors or teams. For more information, see &quot;Creating a pull request.&quot;
        ///
        ///Once you&apos;ve created a pull request, you can push commits from your topic branch to add them to the exi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitRepositories_3b {
            get {
                return ResourceManager.GetString("GitRepositories_3b", resourceCulture);
            }
        }
    }
}
